name: UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Получить код из репозитория
        uses: actions/checkout@v4

      - name: Установить Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Установить зависимости
        run: |
          pip install -r requirements.txt

      - name: Установить браузеры Playwright
        run: playwright install chromium --with-deps

      - name: Запустить тесты
        run: pytest tests/ -v --alluredir=allure-results

      - name: Сохранить Allure-результаты
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results/
