name: UI Tests
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Получить код из репозитория
        uses: actions/checkout@v4
      - name: Собрать и запустить тесты в Docker
        run: docker build -t qa-tests . && docker run qa-tests